### ISSUE TITLE
Sometimes the accuracy filter fails

### ISSUE THREAD

**Issue by AndreiSpatariu** [gergelycsegzi/gmaps-history-to-countries#1]
I think I had some corrupted data in my location history and it did not have the 'accuracy' field. I have changed the filtering block of code to:

for location in locations:
    timestamp = parse(location['timestamp'])
    seconds_from_last_point = (timestamp - previous_timestamp).total_seconds()

    is_valid = ('latitudeE7' in location) & ('longitudeE7' in location) & ('accuracy' in location)
    if (seconds_from_last_point > event_filter_window_in_seconds) & is_valid:
            if int(location['accuracy']) < 200:
                lat = location['latitudeE7']/1e7
                long = location['longitudeE7']/1e7
                coordinates.append((lat, long))
                filtered_locations.append(location)
                previous_timestamp = timestamp

In order to have the key checks before using them

**Comment by gergelycsegzi** [comment]
https://github.com/gergelycsegzi/gmaps-history-to-countries/pull/2
